### ISSUE TITLE
Une documentation pour aider

### ISSUE THREAD

**Issue by hichxm** [bowphp/app#1]
Bonjour, 
le projet a l'air prometteur mais aucune documentation n'est disponible pour aider un futur contributeur ou tout simplement un futur développeur utilisant le framework bow.

Pour faire une documentation rapide, utiliser phpdocumentor ?

**Comment by papac** [comment]
C'est effectivement ça. Nous reconfigurons la page github du framework pour permettre à plusieur de contribuer sur plusieur niveau.

Il y a actuellement le dépot de la [documentation](https://github/bowphp/docs) qui est ouvert.

**Comment by hichxm** [comment]
Merci, mais il y a moyen d'utiliser phpDocumentor aussi pour détailler chaque classe pour les futurs contributeur aussi ?

**Comment by papac** [comment]
Oui biensur. Voici le lien de l'[api](https://bowphp.github.io/api/master) du code mais nous avons utilisé SAMI (C'est un outil symfony).

**Comment by papac** [comment]
Je vous informe qu'il y a maintenant une [documentation](https://github.com/bowphp/docs) que vous pouvez consulter.
