### ISSUE TITLE
[4.0] translate the bowphp/docs to english

### ISSUE THREAD

**Issue by papac** [bowphp/app#13]
Translate all comment of other text in engish.

**Comment by papac** [comment]
Help to translate [bowphp/docs](https://github.com/bowphp/docs) @houssenedao

**Comment by houssenedao** [comment]
@papac you have'd a translate all comments?

**Comment by papac** [comment]
@houssenedao I was talking about translating documentation.
 [bowphp/docs](https://github.com/bowphp/docs).

There are English users who want to try bowphp

**Comment by peter279k** [comment]
Is this issue keep open? The [documentation](https://bowphp.com/docs) are written in France.

**Comment by papac** [comment]
Yes in fact the problem remains open on which we are working!

**Comment by peter279k** [comment]
Thanks. And I think it should reopen this issue and let us keep looking :eyes: !
