### ISSUE TITLE
Add PHP extensions requirement on composer.json

### ISSUE THREAD

**Issue by peter279k** [bowphp/app#50]
According to the [readme.md](https://github.com/bowphp/app/blob/4.0/readme.md), it should require following PHP extensions:

- OpenSSL PHP Extension
- PDO PHP Extension
- Mbstring PHP Extension
- XML PHP Extension
- JSON PHP Extension

After checking the codes, it seems that this repository requires the `pdo_mysql` and `sqlite` extensions.

To make PHP extension checking during `composer update` command running, it should add above PHP extensions in `composer.json` inside `require` block.

**Comment by papac** [comment]
Yes you can update !

**Comment by papac** [comment]
So we want to create the new major version of bowphp

- Version 5
- Rewriting in PHP8
- New route system
- And strong database

**Comment by peter279k** [comment]
@papac, I've created the PR #52. Please review this PR. Thanks!
